import Head from 'next/head'
import styles from '../styles/Home.module.css'

export function MainLayout({children}) {
  return (
  <>
  <div className={styles.container}>
    <Head>
      <title>Mini Insta</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/Instagram_icon-icons.com_66804.ico" />
    </Head>
    <main className={styles.main}>
      <div className={styles.photosContainer}>
        {children}
      </div>
    </main>
    </div>
    </>
  );
}
